version: "3"
services:
  db:
    container_name: db
    image: mysql:8.2.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always
  db-initializer:
    container_name: db-initializer
    links:
      - "db"
    build: db-initializer
    ports:
      - "5001:5000"
    depends_on:
      - db
    env_file:
      - ./db-initializer/.env

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

