version: "3"
services:
  db:
    container_name: db
    image: mysql:8.2.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always

  db-initializer:
    container_name: db-initializer
    links:
      - "db"
    build: db-initializer
    ports:
      - "5001:5000"
    depends_on:
      - db
    env_file:
      - ./db-initializer/.env
    healthcheck:
      test: ["CMD", "test", "-f", "tmp/initializer_complete"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - shared-data:/tmp

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - db-initializer
    volumes:
      - shared-data:/tmp


volumes:
  shared-data:

